version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - aws ecr get-login-password | docker login --username AWS --password-stdin 741989928127.dkr.ecr.us-east-1.amazonaws.com/trialdockerfile
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
     
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - echo Path `pwd` 
      - echo Permissions `ls -la` 
      - chmod -R 775 ml_model_train_test_code
      - echo ml_model_train_test_code Permissions `cd ml_model_train_test_code && ls -la`     
      - docker build -t trialdockerfile .
      - docker tag trialdockerfile 741989928127.dkr.ecr.eu-west-1.amazonaws.com/trialdockerfile     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 741989928127.dkr.ecr.eu-west-1.amazonaws.com/trialdockerfile
